# include <iostream.h>
# include <conio.h>
   main() {
   char nama [30];
   float jurusan,nk,nt1,nt2,nt3,nmid,nquis,nfinal,tnt,na;
    cout<<"hitung nilai akhir"<<end1;
    cout<<"masukan nama mahasiswa:";cin>>nm;
    cout<<"masukan jurusan mahasiswa:";cin>>jurusan;
    cout<<"masukan nilai kehadiran :";cin>>nk;
    cout<<"masukan nilai tugas1:";cin>>nt1;
    cout<<"masukan nilai tugas2 :";cin>>nt2;
    cout<<"masukan nilai tugas3 :";cin>>nt3;
    cout<<"masukan nilai mid :";cin>>nmid;
    cout<<"masukan nilai quis:";cin>>nquis;
    cout<<"masukan nilai final :";cin>>nfinal;
    tnt = nt1+nt2+nt3/3
    na=(20%*nt)+(20%*tnt)+(20%*nmid)+(20%*nquis)+(20%nilai final)
    cout<<"siswa yang bernama"<<jurusan<<end1;
    cout<<"jurusan"<<jurusan<<end1;
    cout<<"nilai akhir"<<nk<<end1;
    getc() }
